Crud titulos
The-Cowboys/tonto-apy pull request #12
Opened 2024-06-03 20:49 UTC by MallicTesla

endpoit para titulos
obtener todos los titulos
obtener un titulo por id 
editar un titulo
borrar un titulo

2024-06-07 09:37 UTC, francosang submitted a review, later dismissed

2024-06-07 09:37 UTC, francosang commented on titulos/crud.py
> +    return None
Acordate de ser consistente con los tipos de retorno.
Una funcion tiene que retornar una cosa.

Aca estar retornando un Booleano o un None.
Yo retornaría False en lugar de None.

2024-06-07 22:05 UTC, MallicTesla commented
ya solucione todo los problemas y conflictos

2024-06-12 09:53 UTC, francosang approved these changes

2024-06-12 09:53 UTC, francosang commented on titulos/crud.py
> +from sqlalchemy.orm import Session, joinedload
El `joinedload` no se usa, verdad?

2024-06-12 09:53 UTC, francosang commented on .gitignore
> +routers_tonto
Por que el archivo de rutas esta ignorado? 
Quisiste poner `routers_tonto.py`?

2024-06-12 09:53 UTC, francosang commented on tontos/routers_tonto.py
> +def crear_cowboy (db: Session = Depends (bd_coneccion.get_db), cowboy: schemas.CrearCowboy = Body(...)):
Que es esto?
Por que no esta agregado a las rutas?
Por que la url es `POST /seleccionar` y crea un cowboy?

Para crear un cowboy seria `POST api/cowboys`.

2024-06-12 09:54 UTC, francosang requested changes
😈

2024-06-14 11:50 UTC, francosang approved these changes

2024-06-16 21:06 UTC, merged